// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjvwB9UcOjf7GwZ6sG4fDYzMqEqyS0HGk',
    appId: '1:695778282180:android:1f46b789f5605b71445791',
    messagingSenderId: '695778282180',
    projectId: 'hycharge-97c01',
    databaseURL: 'https://hycharge-97c01-default-rtdb.firebaseio.com',
    storageBucket: 'hycharge-97c01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjImpCClMWuSBEMPuRD_QL55vRXVPP0GE',
    appId: '1:695778282180:ios:ff943a2c13960cc4445791',
    messagingSenderId: '695778282180',
    projectId: 'hycharge-97c01',
    databaseURL: 'https://hycharge-97c01-default-rtdb.firebaseio.com',
    storageBucket: 'hycharge-97c01.appspot.com',
    iosClientId: '695778282180-os4d7e4fad0vft4iq1d5kh68ksknlccp.apps.googleusercontent.com',
    iosBundleId: 'com.hycharge.app',
  );
}
